-- Create profiles table to handle roles
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;

-- Policy handling (drop if exists to allow re-running)
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create site_content table
create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  section text not null,
  key text not null unique,
  value jsonb not null,
  label text,
  type text default 'text', -- 'text', 'textarea', 'json', 'image'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.site_content enable row level security;

drop policy if exists "Site content is viewable by everyone." on site_content;
create policy "Site content is viewable by everyone."
  on site_content for select
  using ( true );

drop policy if exists "Site content is editable by admins only." on site_content;
create policy "Site content is editable by admins only."
  on site_content for all
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- Trigger to handle new user signup (automatically create profile)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'user');
  return new;
end;
$$;

-- Safely create trigger
do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'on_auth_user_created') then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.handle_new_user();
  end if;
end
$$;

-- Initial Data for Services Page (Upsert to avoid duplicates)
insert into site_content (section, key, value, label, type) values
('services', 'page_title', '"I Nostri Servizi"', 'Titolo Pagina', 'text'),
('services', 'page_subtitle', '"Dalla ripresa alla post-produzione, offriamo un ecosistema completo per il video."', 'Sottotitolo Pagina', 'textarea'),
('services', 'services_list', '[
    { 
        "title": "Noleggio Studio", 
        "desc": "Spazio insonorizzato e climatizzato, ideale per registrazioni video e shooting. Dotato di green screen, fondali colorati e limbo bianco.", 
        "img": "/images/S3.jpg",
        "features": ["Green Screen", "Limbo 6x6m", "Luci abinabili", "Camerini"]
    },
    { 
        "title": "Regia Mobile & Fissa", 
        "desc": "Sistemi di regia completi per gestire produzioni multicamera sia in studio che in esterna. Tecnologie 4K e workflow SDI.", 
        "img": "/images/REG1.jpg",
        "features": ["Mixer Video 4K", "Regia Audio Digitale", "Intercom", "Replay System"]
    },
    { 
        "title": "Personale Tecnico", 
        "desc": "Un team di professionisti pronti a supportarti. Registi, cameraman, fonici, direttori della fotografia e tecnici luci.", 
        "img": "/images/R2.jpg",
        "features": ["Registi", "DOP", "Cameraman", "Fonici"]
    },
    { 
        "title": "Live Streaming", 
        "desc": "Porta il tuo evento ovunque. Servizi di streaming professionale su tutte le piattaforme con encoding hardware ridondato.", 
        "img": "/images/U1.jpg",
        "features": ["Multi-platform", "Backup 4G/5G", "Grafica Live", "Interazione Social"]
    },
    { 
        "title": "Post-Produzione", 
        "desc": "Diamo il tocco finale al tuo video. Montaggio, color correction, sound design e motion graphics di alto livello.", 
        "img": "/images/E4.jpg",
        "features": ["Editing 4K", "Color Grade", "VFX", "Mixaggio Audio"]
    },
    { 
        "title": "Eventi Aziendali", 
        "desc": "Supporto tecnico completo per convention, webinar, meeting e lanci di prodotto. Trasformiamo eventi in show televisivi.", 
        "img": "/images/E2.jpg",
        "features": ["Proiezione", "Allestimento Stage", "Audio Sala", "Diretta Video"]
    }
]', 'Lista Servizi', 'json')
on conflict (key) do nothing;
